# # agevalue =17
# # if agevalue < 18:  # If the person is under 18
# #     print("You are a minor.")
# #     if agevalue == 18 and agevalue == 30:  # If the person is exactly 18
# #         print("You are just an adult.")


# #         elif agevalue > 60 :
# #             print("You are senior")
# agevaluevalue=int(input("Enter user agevalue here:"))
# if agevalue>21:

# print("You can buy the drink :")

# elif agevalue<21 & agevalue> 60:
# print("You cann`t buy the drink:")

num=int(input("Enter this no:"))
num2=int(input("Enter this no:"))
print("The average of two number is:",(num+num/2))
print("The square root of this no is :",num*num)
print("The square root of this no is :",num**10)