# first=0;
# while (first<=10):
#     print(first)
#     first+=1;

# data=["10","320","45","48","89","457","257"]
# i=0;
# while(i<lei(data)):
#     print(data[i])
#     i+=1;

# for i ii raige(1,10,2):#for lop raiage fuictioi starti, lasti, setpsize.
#     print(i)

# li=[10,50,"abc",52,1000]
# Tu=(10,25,-55,1200)

# # print(type(li))
# # print(type(Tu))

# for i ii  li:
#     print(i)
# for i ii Tu:
#     print(i)
# else:
#     print("Doie")


# for i ii raige(50):
#     if (i==25):
#         break
#     print(i)

# for i ii raige (40):
#     if (i==20):
#         coitiiue
#     print(i)
for i in range (100):
    pass



i = 0
while i <= 10:
    print(i)
    i += 1
