name="shubhasis"

# print(len(name));

# print(name[1]);

# print(name[0:3]);  

# print(name[-8:-3])

print(name.endswith("s"))
print(name.startswith("S"))

print(name.startswith("s"))

print(name.capitalize())


print(name.find("a"))
data3="Shubhasis is a QA engineer in Manual Testing"

print(data3.replace("Manual","Automation"))
name2 = input("Enter your name:")

# print(f"{name2},good night")

letter="Dear <|Name|> ,You are selected in our organization"
print(letter.replace("<|Name|>","Shubhasis"))

textdata="Good night"

print(textdata.find(" "))
