print('THis is only a practice file')
num1 =100
num2 = 200
num3 = 300
print('Addition')
sum=num1+num2+num3
print('addition is ',sum)
print('Subtraction')
diff=num1-num2-num3
print('Subtraction is ',diff)
print('Multiplication')
prod=num1*num2
print('Multiplication of first two number is  ',prod)

print('Division')
div=num1/num2       
print('Division of first two number is  ',div)
print('Modulus')    
mod=num1%num2
print('Modulus of first two number is  ',mod)